const menu = [
    {
        id:1,
        title:"burger",
        category:"Fast Food",
        price:"1",
        img:"/images/burger.jpg",
        desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Saepe tempore molestias porro inventore sapiente! Eos provident suscipit, id porro corrupti corporis excepturi ea ad ab reiciendis mollitia dolore enim expedita.",
    },
    {
        id:2,
        title:"pizza",
        category:"Fast Food",
        price:"2",
        img:"/images/pizza.jpg",
        desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Saepe tempore molestias porro inventore sapiente! Eos provident suscipit, id porro corrupti corporis excepturi ea ad ab reiciendis mollitia dolore enim expedita.",
    },
    {
        id:3,
        title:"sandwich",
        category:"Fast Food",
        price:"1",
        img:"/images/sandwich.jpg",
        desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Saepe tempore molestias porro inventore sapiente! Eos provident suscipit, id porro corrupti corporis excepturi ea ad ab reiciendis mollitia dolore enim expedita.",
    },
    {
        id:4,
        title:"fried chicken",
        category:"Non-Veg",
        price:"4",
        img:"/images/fried-chicken.jpg",
        desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Saepe tempore molestias porro inventore sapiente! Eos provident suscipit, id porro corrupti corporis excepturi ea ad ab reiciendis mollitia dolore enim expedita.",
    },
    {
        id:5,
        title:"fish fingers",
        category:"Non-Veg",
        price:"4",
        img:"/images/fish-finger.jpg",
        desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Saepe tempore molestias porro inventore sapiente! Eos provident suscipit, id porro corrupti corporis excepturi ea ad ab reiciendis mollitia dolore enim expedita.",
    },
    {
        id:6,
        title:'dal makhani',
        category:'veg',
        price:'3',
        img:'./images/dal-makhani.jpg',
        desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Saepe tempore molestias porro inventore sapiente! Eos provident suscipit, id porro corrupti corporis excepturi ea ad ab reiciendis mollitia dolore enim expedita.",
    },
    {
        id:7,
        title:'kofta',
        category:'veg',
        price:'5',
        img:'./images/kofta.jpg',
        desc:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Saepe tempore molestias porro inventore sapiente! Eos provident suscipit, id porro corrupti corporis excepturi ea ad ab reiciendis mollitia dolore enim expedita.',
    },
    {
        id:8,
        title:'burritos',
        category:'veg',
        price:'4',
        img:'./images/burritos.jpg',
        desc:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Saepe tempore molestias porro inventore sapiente! Eos provident suscipit, id porro corrupti corporis excepturi ea ad ab reiciendis mollitia dolore enim expedita.',
    },
    {
        id:9,
        title:'masala chai',
        category:'beverages',
        price:'1',
        img:'./images/masala-chai.jpg',
        desc:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Saepe tempore molestias porro inventore sapiente! Eos provident suscipit, id porro corrupti corporis excepturi ea ad ab reiciendis mollitia dolore enim expedita.',
    },
    {
        id:10,
        title:'coffee',
        category:'beverages',
        price:'1',
        img:'./images/coffee.jpg',
        desc:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Saepe tempore molestias porro inventore sapiente! Eos provident suscipit, id porro corrupti corporis excepturi ea ad ab reiciendis mollitia dolore enim expedita.',
    },
];

